version: "2"
services:
  container-api:
    image: gcr.io/${PROJECT_ID}/${SERVICE}:${GITHUB_SHA}
    command: npm run start
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - .:/app
